#!/usr/bin/zsh
##vim:filetype=zsh
# -- coloured manuals
function man() {
  env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

function release_to_msm() {
    ssh msm mkdir /tftpboot/tintagel/REL_4D_${1}
    scp REL_4D_${1}* msm:/tftpboot/tintagel/REL_4D_${1}/
}

function vman() {
    nvim -c "Man $1 $2" -c 'silent only'
}

if [ "${INSIDE_CONTAINER}" = "no" ]
then
    function tvim() {
        dir=`pwd | sed -e "s;.*4P_Overlay;;" -e "s;/home/jeremyro;~;"`
        if which nvim > /dev/null
        then
            cmd="nvim -p $@"
        else
            cmd="vim -p $@"
        fi
        cols=`tput cols`
        if [ -n "$TMUX" ];
        then
            if [ ${cols} -lt 130 ]
            then
                eval ${cmd}
            else
                tmux split-window -h "${cmd}" \; \
                    select-layout main-vertical
            fi
        else
            if [ ${cols} -lt 130 ]
            then
                tmux new-session -d "${cmd}" \; \
                    attach 
            else
                tmux new-session \; \
                    split-window -h "${cmd}" \; \
                    select-layout main-vertical \; \
                    attach 
            fi
        fi
    }

    function ssh-builder() {
        local BUILDER_IP=`grep ${1} /var/lib/misc/dnsmasq.lxcbr0.leases | awk '{print $3}'`
        if [ -n "${BUILDER_IP}" ]
        then
            ssh -A ${BUILDER_IP}
        else
            echo "Cannot find ip for ${1}"
        fi
    }
fi

function list_subrepos() {
    if [ $# != 1 ]
    then
        print -u2 "ERROR: Only one argument required."
        print -u2 "$0 PARENT_PATH"
        return 1
    fi

    parent_repo=${1}
    ssh -p 29418 rndgit gerrit ls-projects --type code | grep ${parent_repo}
}

function list_zuul_subrepos() {
    if [ $# != 1 ]
    then
        print -u2 "ERROR: Only one argument required."
        print -u2 "$0 PARENT_PATH"
        return 1
    fi
    parent_repo=${1}

    ssh rnddevtools "grep ${parent_repo} /etc/zuul/layout.yaml" | sed -e 's/.*name: //'
}

function list_non_zuul_subrepos() {
    if [ $# != 1 ]
    then
        print -u2 "ERROR: Only one argument required."
        print -u2 "$0 PARENT_PATH"
        return 1
    fi

    parent_repo=${1}
    all_subrepos=$(list_subrepos ${parent_repo})
    all_file=$(mktemp)
    echo ${all_subrepos} > ${all_file}

    zuul_subrepos=$(list_zuul_subrepos ${parent_repo})
    zuul_file=$(mktemp)
    echo ${zuul_subrepos} > ${zuul_file}

    diff --suppress-common-lines --color=always ${all_file} ${zuul_file} | grep "^[+-]\<"
    rm ${all_file} ${zuul_file} 
}

function checkout_subrepos() {
    if [ $# != 1 ]
    then
        print -u2 "ERROR: Only one argument required."
        print -u2 "$0 PARENT_PATH"
        return 1
    fi

    parent_repo=${1}
    for repo in `ssh -p 29418 rndgit gerrit ls-projects --type code | grep ${parent_repo}`
    do
        repo_subpath=$(echo ${repo} | sed -e "s|${parent_repo}/||")
        if [ -d ${repo_subpath} ]
        then
            pushd $repo_subpath
            git pull
            popd
        else
            git clone ssh://jeremyro@rndgit:29418/$repo $repo_subpath
        fi
    done
}
